version: '3'
services:
  protoshock-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: protoshock-server
    container_name: protoshock-server
    ports:
      - "8880:8880"
    restart: always
